version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
          - node_modules
      - run: yarn lint

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
